development:
  DATABASE_URL: sqlite://app/db/store/development.db
  DB_KEY: S42jFKity8UJ+dYs9HzTzVHYDuoZmTLeriC47HTdeHY=
  SECURE_SCHEME: HTTP
  MSG_KEY: QwsjC6WdxnNYjiWn5qOFp4xBRFcWY+wjrARjV0Vz3cA=
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTP
  GITHUB_ACCOUNT_URL: https://api.github.com/user
  SIGNING_KEY: PlXax5f9PwGIn9cO5jte1FB7w2h8etDi4giEQUYxElE=
  VERIFY_KEY: ZYuoIiVdICHUe3tKlQ4sYyhouHpz4z1wtgK56UPTTUE=

test:
  DATABASE_URL: sqlite://app/db/store/test.db
  DB_KEY: S42jFKity8UJ+dYs9HzTzVHYDuoZmTLeriC47HTdeHY=
  SECURE_SCHEME: HTTP
  MSG_KEY: QwsjC6WdxnNYjiWn5qOFp4xBRFcWY+wjrARjV0Vz3cA=
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTP
  GITHUB_ACCOUNT_URL: https://api.github.com/user
  SIGNING_KEY: PlXax5f9PwGIn9cO5jte1FB7w2h8etDi4giEQUYxElE=
  VERIFY_KEY: ZYuoIiVdICHUe3tKlQ4sYyhouHpz4z1wtgK56UPTTUE=

production:
  DATABASE_URL: <do not set - set directly on production server>
  SECURE_SCHEME: HTTPS
  MSG_KEY: QwsjC6WdxnNYjiWn5qOFp4xBRFcWY+wjrARjV0Vz3cA=
  SENDGRID_API_KEY: <provision new API key on SendGrid>
  SENDGRID_FROM_EMAIL: <provision single sender email address on SendGrid>
  SECURE_SCHEME: HTTP
  GITHUB_ACCOUNT_URL: https://api.github.com/user
  SIGNING_KEY: PlXax5f9PwGIn9cO5jte1FB7w2h8etDi4giEQUYxElE=
  VERIFY_KEY: ZYuoIiVdICHUe3tKlQ4sYyhouHpz4z1wtgK56UPTTUE=